Signup backend
SophieUdud/MentorAmp pull request #10
Opened 2021-04-18 07:43 UTC by siriuscoder108

## Add backend logic to the Signup Component

**This PR addresses the Asana Task:** [Add backend logic to the Signup Component](<https://app.asana.com/0/1200052110995462/1199873427042143/f>)

### Features of this PR

1. Display the signup modal and asks whether user is mentor or mentee,
2. Displays the signup modal with current Salesforce user's name, email and phone in user info modal.
3. Displays the list of skills.
4. Creates a new MentorAmp_User record with recordtypeId matching either mentor or mentee type and saves the user info -- except for skills.
5. Displays successfully signed up message and dismisses all modals

Then provide an organized and clear summary of the changes you've made to achieve this.

**You can use bullet points to describe your changes**
- Added new classes to: 

1. Determine recordTypeId 
2. Get current logged in user's info  (name, email, phone) to display in user signup modal
3. Save user info to MentorAmp_user record with recordTypeId from 1

### Steps to Verify and Test Changes
Please describe the tests that you've performed to verify your changes. Provide instruction steps to reproduce the changes.
- [X] Launched Signup with temporary signup button 
- [X] Verified that correct user info displayed in user modal
- [X] Verified that record was saved correctly when Save button was clicked

### Checklist:
Please insert an X inside the brackets to check off each item. All items are to be completed.

- [X] I have performed a self-review of my own code
- [ ] I have commented my code appropriately, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added necessary unit tests
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### Before Screenshots
n/a

### After Screenshots
![image](https://user-images.githubusercontent.com/72955443/115137995-425ed780-9fde-11eb-98fe-efa6062734cd.png)

![image](https://user-images.githubusercontent.com/72955443/115138008-599dc500-9fde-11eb-951f-b7da6743fab4.png)

![image](https://user-images.githubusercontent.com/72955443/115138019-6d492b80-9fde-11eb-93db-41226e5b7871.png)

<img width="1366" alt="Screen Shot 2021-04-18 at 12 42 00 AM" src="https://user-images.githubusercontent.com/72955443/115138121-198b1200-9fdf-11eb-9cbf-3071818be178.png">

2021-04-20 03:46 UTC, SophieUdud requested changes
Hi Bhakti, nice work! ✨ 
I left some comments, but the 2 marked as ** Please don't merge before fixing this ** are the ones with functional bugs that needs to be fixed in order to merge this PR. All other comments are about code-health and having a clean codebase. If you have some time you can either fix them now or maybe in the next round in the clean-up ticket, as they won't cause any functional errors for now.
Feel free to reach out if you have any questions or need clarification about anything 😃 
Thank you very much! 🙏

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/classes/MentorUserController.cls
> +            insert user;
** Please don't merge before fixing this **
We have a User__c custom field on the MentorAmp_User__c object, that needs to be populated with the currently logged-in User's Id before inserting the record. Please do it either here before the insert line (user.User__c = UserInfo.getUserId()) or in the signup.js submitDetails() function. If this field is not populated, the new mentorAmpUser won't be associated with any salesforce Users, so it wouldn't be any use. Thank you!

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/main/main.js
> +export default class Main extends LightningElement {
** Please don't merge before fixing this **
We already have this line in line 60, it probably comes from the merge conflict, but please delete it as right now it causes deployment issues. Thank you!

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/signup/signup.html
> +		<template if:true={isSavedSuccess}>
Is this template (line 5-19) still being used? None of the properties or functions ({_title}, {message}, {variantChanged} etc.) are defined in the js, and it's not even showing up. If it's not being used anymore could you please delete it?

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/signup/signup.html
> +					<template if:true={user}>
Where is {user} property declared in the js file? I see that it's set in line 44 in the js file, but I don't see the property/variable originally declared anywhere (like the ones in lines 13-22)

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/signup/signup.html
> +						<template if:false={user}>
If {user} stores the currently logged-in user's data, then this will never be false as there's always a logged-in salesforce user when the component is displayed :) if I understand it well and this is the case, then the if:true statement above is not necessary, just as this if:false part as it will never show up

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/signup/signup.js
> +import getMentorRecordType from '@salesforce/apex/RecordTypeController.getMentorRecordType';
It looks like currently you are not using the getMenteeRecordType and getMentorRecordType functions, as you're getting the recordTypes from the getObjectInfo function. Importing these functions are unnecessary then, just as the whole RecordTypeController apex class, as it's never being called.
Same for importing the getRecord function, currently it's not being used anywhere.

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/signup/signup.js
> +            this.isSavedSuccess = true;
The isSavedSuccess property is true by default (line 20) so why set it now? Also, if the html part displayed when isSavedSuccess is true is not needed anymore (is it?) then this property is unnecessary too.

2021-04-20 03:46 UTC, SophieUdud commented on force-app/main/default/lwc/signup/signup.js
> +    showNotification(title, message, variant) {
Nice job with the reusable function! 😃 💯

2021-04-20 04:11 UTC, siriuscoder108 commented on force-app/main/default/lwc/main/main.js
> +export default class Main extends LightningElement {
Done.

2021-04-20 04:25 UTC, siriuscoder108 commented on force-app/main/default/lwc/signup/signup.html
> +		<template if:true={isSavedSuccess}>
This is the skills placeholder. We're not currently saving it, but I think it's good to keep it in here.

2021-04-20 04:25 UTC, siriuscoder108 commented on force-app/main/default/lwc/signup/signup.html
> +						<template if:false={user}>
It's defined here
   submitDetails() {
        // The skills is not being saved at this time need design
        // of how to handle saving skills
        this.isModalOpen = false;
        let user = { 'sobjectType': 'MentorAmp_User__c' };
        user.Name__c= this.userName;
        user.Email__c = this.userEmail;
        user.Phone__c = this.userMobile;
        if (this.isMentor) {
            user.RecordTypeId = this.mentorRecordTypeId;
        } else {
            user.RecordTypeId = this.menteeRecordTypeId;
        }
        this.saveRecord(user);
        this.closeModal();
    }

2021-04-20 04:25 UTC, siriuscoder108 commented on force-app/main/default/lwc/signup/signup.html
> +						<template if:false={user}>
It's impossible to not have a currently logged in user running the app the way I see it.

2021-04-20 04:25 UTC, siriuscoder108 commented on force-app/main/default/lwc/signup/signup.js
> +import getMentorRecordType from '@salesforce/apex/RecordTypeController.getMentorRecordType';
Yes, was an attempted solution. Cleaned it up.

2021-04-20 04:25 UTC, siriuscoder108 commented on force-app/main/default/lwc/signup/signup.js
> +            this.isSavedSuccess = true;
This displays the "Successfully signed up toast".

2021-04-20 04:42 UTC, SophieUdud submitted a review, later dismissed
Thank you for fixing everything in such short time! Amazing job! Thank you very much! 🙏 ✨ 🥇

2021-04-20 17:36 UTC, SophieUdud approved these changes
💯

2021-04-21 01:41 UTC, harshilonline approved these changes
👍

2021-04-21 03:34 UTC, merged